# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: João Bordalo
email: joao.bordalo@gmail.com
description: Hello, I'm João Bordalo, a full stack developer living in Portugal. Here you can see some of my work, know my history or get my CV. Feel free to reach out.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://joaobordalo.com'
og_image: https://cdn.joaobordalo.com/images/static/logos/logo_circle.png
cdn_url: https://cdn.joaobordalo.com/images/static

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-paginate

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/blog/page:num/'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github_url: https://github.com/bordalix
nostr_url: https://snort.social/p/npub1vt803quxxq32fuwkp42g2lyaw2t9qupvnl3z0vyc3s9kudkyhn8qt28cxv
stackoverflow_url: https://stackoverflow.com/users/7006174/bordalix
twitter_url: https://twitter.com/bordalix
