# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: João Bordalo
email: joao.bordalo@gmail.com
description: Hello, I'm João Bordalo, a full stack bitcoiner living in Portugal. Here you can see some of my work, know my history or get my CV. Feel free to reach out.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://joaobordalo.com'
og_image: https://joaobordalo.com/images/static/logos/logo_circle.png
cdn_url: /images/static

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-paginate

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/blog/page:num/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github_url: https://github.com/bordalix
stackoverflow_url: https://stackoverflow.com/users/7006174/bordalix
twitter_url: https://twitter.com/bordalix

portfolio:
  - blob: appcexplorer
    name: 'APPC Explorer'
  - blob: appcoins
    name: 'Appcoins'
  - blob: batalhadosbitaites
    name: 'Batalha dos Bitaites'
  - blob: bitcoinstats
    name: 'Bitcoinstats'
  - blob: catappult
    name: 'Catappult'
  - blob: chesstr
    name: 'Chesstr'
  - blob: cowork
    name: 'CoWork Azeitão'
  - blob: dogoffleash
    name: 'Dog off leash'
  - blob: ethereum-roulette
    name: 'Ethereum Roulette'
  - blob: fuji
    name: 'Fuji Money'
  - blob: hatitude
    name: 'Hatitude'
  - blob: helm
    name: 'Helm wallet'
  - blob: iscore
    name: 'iScore'
  - blob: nostr-utils
    name: 'Nostr Utils'
  - blob: tdex
    name: 'TDEX'
  - blob: wheretosurftoday
    name: 'Where to surf today'

skills:
  - HTML:
    name: 'HTML'
    icon: 'html.svg'
  - CSS:
    name: 'CSS'
    icon: 'css.svg'
  - Javascript:
    name: 'Javascript'
    icon: 'js.svg'
  - Typescript:
    name: 'Typescript'
    icon: 'ts.svg'
  - React:
    name: 'React'
    icon: 'react.svg'
  - Svelte:
    name: 'Svelte'
    icon: 'svelte.svg'
  - Expo:
    name: 'Expo'
    icon: 'expo.svg'
  - NextJS:
    name: 'NextJS'
    icon: 'nextjs.svg'
  - PostgreSQL:
    name: 'PostgreSQL'
    icon: 'postgresql.svg'
  - BitcoinJS:
    name: 'Bitcoin'
    icon: 'bitcoin.svg'
  - Liquid:
    name: 'Liquid'
    icon: 'liquid.svg'
  - Lightning:
    name: 'Lightning'
    icon: 'lightning.svg'
