# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: João Bordalo
email: joao.bordalo@gmail.com
description: Hello, I'm João Bordalo, a full stack bitcoiner living in Portugal. Here you can see some of my work, know my history or get my CV. Feel free to reach out.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://joaobordalo.com'
og_image: https://joaobordalo.com/images/static/logos/logo_circle.png
cdn_url: /images/static

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-paginate

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/blog/page:num/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github_url: https://github.com/bordalix
stackoverflow_url: https://stackoverflow.com/users/7006174/bordalix
twitter_url: https://twitter.com/bordalix

portfolio:
  - blob: appcexplorer
    name: 'APPC Explorer'
  - blob: appcoins
    name: 'Appcoins'
  - blob: arkade
    name: 'Arkade'
  - blob: batalhadosbitaites
    name: 'Batalha dos Bitaites'
  - blob: bitcoinstats
    name: 'Bitcoinstats'
  - blob: catappult
    name: 'Catappult'
  - blob: chesstr
    name: 'Chesstr'
  - blob: cowork
    name: 'CoWork Azeitão'
  - blob: dogoffleash
    name: 'Dog off leash'
  - blob: ethereum-roulette
    name: 'Ethereum Roulette'
  - blob: fuji
    name: 'Fuji Money'
  - blob: fulmine
    name: 'Fulmine'
  - blob: hatitude
    name: 'Hatitude'
  - blob: helm
    name: 'Helm wallet'
  - blob: iscore
    name: 'iScore'
  - blob: marina
    name: 'Marina'
  - blob: nostr-utils
    name: 'Nostr Utils'
  - blob: tdex
    name: 'TDEX'
  - blob: wheretosurftoday
    name: 'Where to surf today'
  - blob: worldleague
    name: 'World League'

skills:
  - HTML:
    name: 'HTML'
    icon: 'html.svg'
  - CSS:
    name: 'CSS'
    icon: 'css.svg'
  - Javascript:
    name: 'Javascript'
    icon: 'js.svg'
  - Typescript:
    name: 'Typescript'
    icon: 'ts.svg'
  - React:
    name: 'React'
    icon: 'react.svg'
  - Svelte:
    name: 'Svelte'
    icon: 'svelte.svg'
  - Expo:
    name: 'Expo'
    icon: 'expo.svg'
  - NextJS:
    name: 'NextJS'
    icon: 'nextjs.svg'
  - PostgreSQL:
    name: 'PostgreSQL'
    icon: 'postgresql.svg'
  - BitcoinJS:
    name: 'Bitcoin'
    icon: 'bitcoin.svg'
  - Liquid:
    name: 'Liquid'
    icon: 'liquid.svg'
  - Lightning:
    name: 'Lightning'
    icon: 'lightning.svg'

experience:
  - name: 'Minho University'
    role: 'Computer Science Student'
    start_date: 'Sep 1990'
    end_date: 'May 1996'
    description: 'Complementary studies in cryptography and distributed operating systems'
    tags:
      - 'Cryptography'
      - 'Distributed Systems'
  - name: 'IDITE-Minho'
    role: 'Project Manager'
    start_date: 'Sep 1990'
    end_date: 'May 1996'
    description: 'EU project, with coordination of teams in several EU countries'
    tags:
      - 'HTML & JavaScript'
      - 'Project Management'
  - name: 'Telenet ISP'
    role: 'Systems engineer'
    start_date: 'Jun 1996'
    end_date: 'May 1998'
    description: "ISP's mail system engineer"
    tags:
      - 'Perl, C, PHP'
      - 'IP, TCP & UDP'
      - 'Linux, Solaris & FreeBSD'
  - name: 'IP Global ISP'
    role: 'Systems engineer'
    start_date: 'Apr 1998'
    end_date: 'Apr 1999'
    description: "ISP's provisioning system<br />Network security officer"
    tags:
      - 'Apache'
      - 'Oracle'
      - 'Mysql'
      - 'LDAP'
      - 'Security'
  - name: 'Novis ISP'
    role: 'Systems engineer'
    start_date: 'May 1999'
    end_date: 'Feb 2002'
    description: 'Mail, proxy, DNS and AAA admin<br />Network security officer'
    tags:
      - 'SMTP, POP3 & IMAP'
      - 'HTTP, DNS & Radius'
      - 'Qmail, Squid, BIND & Djbdns'
  - name: 'Clix Portal'
    role: 'CTO'
    start_date: 'Mar 2002'
    end_date: 'Apr 2006'
    description: 'Overall technical guidance<br />R&D of new portal products and services'
    tags:
      - 'DOCSIS, ADSL, UMTS, EDGE, HSDPA & WiFi'
      - 'Portal, CMS & Advertising'
  - name: 'Excentric digital agency'
    role: 'Partner'
    start_date: 'Jul 2006'
    end_date: 'Dec 2015'
    description: 'Digital marketing<br />Innovation and R&D'
    tags:
      - 'Digital Marketing & Advertising'
      - 'Management'
  - name: 'Freelancer'
    role: 'Full stack Developer'
    start_date: 'Jan 2016'
    end_date: 'Present'
    description: 'Development of web apps<br />Consulting and advising'
    tags:
      - 'AI & ML'
      - 'AWS, Docker & Kubernetes'
      - 'Bitcoin'

opensource:
  - name: 'Bitcoin stats'
    description: 'Dashboard with generic stats about Bitcoin'
    url: 'https://github.com/bordalix/bitcoinstats'
  - name: 'Helm wallet'
    description: 'Lightning wallet even your grandma can use'
    url: 'https://github.com/bordalix/helm-wallet'
  - name: 'Chesstr'
    description: 'Chessboard powered by Nostr'
    url: 'https://github.com/bordalix/chesstr'
  - name: 'nhop'
    description: 'A client side only Nostr navigator'
    url: 'https://github.com/bordalix/nhop'
  - name: 'Paywally'
    description: 'Client side cashu paywall'
    url: 'https://github.com/bordalix/paywally'

projects:
  - name: 'Arkade wallet'
    description: 'The entry-point to the Arkade ecosystem'
    url: '/portfolio/arkade.html'
  - name: 'Fuji Money'
    description: 'Non custodial Bitcoin-backed stablecoin'
    url: '/portfolio/fuji.html'
  - name: 'Fulmine'
    description: 'Arkade wallet daemon'
    url: '/portfolio/fulmine.html'
  - name: 'Marina'
    description: 'Liquid wallet browser extension'
    url: '/portfolio/marina.html'
  - name: 'WTST'
    description: 'Find the best places to surf in Portugal'
    url: '/portfolio/wtst.html'
